// Code generated by protoc-gen-go.
// source: proto/indigo_service.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/indigo_service.proto

It has these top-level messages:
	CreateIndexRequest
	CreateIndexResponse
	DeleteIndexRequest
	DeleteIndexResponse
	GetStatsRequest
	GetStatsResponse
	GetMappingRequest
	GetMappingResponse
	IndexDocumentRequest
	IndexDocumentResponse
	DeleteDocumentRequest
	DeleteDocumentResponse
	IndexDocumentsRequest
	IndexDocumentsResponse
	DeleteDocumentsRequest
	DeleteDocumentsResponse
	SearchDocumentsRequest
	SearchDocumentsResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateIndexRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Mapping []byte `protobuf:"bytes,2,opt,name=mapping,proto3" json:"mapping,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Store   string `protobuf:"bytes,4,opt,name=store" json:"store,omitempty"`
}

func (m *CreateIndexRequest) Reset()                    { *m = CreateIndexRequest{} }
func (m *CreateIndexRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateIndexRequest) ProtoMessage()               {}
func (*CreateIndexRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateIndexRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateIndexRequest) GetMapping() []byte {
	if m != nil {
		return m.Mapping
	}
	return nil
}

func (m *CreateIndexRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateIndexRequest) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

type CreateIndexResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateIndexResponse) Reset()                    { *m = CreateIndexResponse{} }
func (m *CreateIndexResponse) String() string            { return proto1.CompactTextString(m) }
func (*CreateIndexResponse) ProtoMessage()               {}
func (*CreateIndexResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateIndexResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteIndexRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteIndexRequest) Reset()                    { *m = DeleteIndexRequest{} }
func (m *DeleteIndexRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteIndexRequest) ProtoMessage()               {}
func (*DeleteIndexRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteIndexRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteIndexResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteIndexResponse) Reset()                    { *m = DeleteIndexResponse{} }
func (m *DeleteIndexResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeleteIndexResponse) ProtoMessage()               {}
func (*DeleteIndexResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteIndexResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetStatsRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetStatsRequest) Reset()                    { *m = GetStatsRequest{} }
func (m *GetStatsRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetStatsRequest) ProtoMessage()               {}
func (*GetStatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetStatsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetStatsResponse struct {
	Stats []byte `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (m *GetStatsResponse) Reset()                    { *m = GetStatsResponse{} }
func (m *GetStatsResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetStatsResponse) ProtoMessage()               {}
func (*GetStatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetStatsResponse) GetStats() []byte {
	if m != nil {
		return m.Stats
	}
	return nil
}

type GetMappingRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetMappingRequest) Reset()                    { *m = GetMappingRequest{} }
func (m *GetMappingRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetMappingRequest) ProtoMessage()               {}
func (*GetMappingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetMappingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetMappingResponse struct {
	Mapping []byte `protobuf:"bytes,1,opt,name=mapping,proto3" json:"mapping,omitempty"`
}

func (m *GetMappingResponse) Reset()                    { *m = GetMappingResponse{} }
func (m *GetMappingResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetMappingResponse) ProtoMessage()               {}
func (*GetMappingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetMappingResponse) GetMapping() []byte {
	if m != nil {
		return m.Mapping
	}
	return nil
}

type IndexDocumentRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id       string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Document []byte `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
}

func (m *IndexDocumentRequest) Reset()                    { *m = IndexDocumentRequest{} }
func (m *IndexDocumentRequest) String() string            { return proto1.CompactTextString(m) }
func (*IndexDocumentRequest) ProtoMessage()               {}
func (*IndexDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IndexDocumentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IndexDocumentRequest) GetDocument() []byte {
	if m != nil {
		return m.Document
	}
	return nil
}

type IndexDocumentResponse struct {
	Count int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *IndexDocumentResponse) Reset()                    { *m = IndexDocumentResponse{} }
func (m *IndexDocumentResponse) String() string            { return proto1.CompactTextString(m) }
func (*IndexDocumentResponse) ProtoMessage()               {}
func (*IndexDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *IndexDocumentResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DeleteDocumentRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDocumentRequest) Reset()                    { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()               {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteDocumentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteDocumentResponse struct {
	Count int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *DeleteDocumentResponse) Reset()                    { *m = DeleteDocumentResponse{} }
func (m *DeleteDocumentResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeleteDocumentResponse) ProtoMessage()               {}
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeleteDocumentResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type IndexDocumentsRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Documents []byte `protobuf:"bytes,2,opt,name=documents,proto3" json:"documents,omitempty"`
	BatchSize int32  `protobuf:"varint,3,opt,name=batchSize" json:"batchSize,omitempty"`
}

func (m *IndexDocumentsRequest) Reset()                    { *m = IndexDocumentsRequest{} }
func (m *IndexDocumentsRequest) String() string            { return proto1.CompactTextString(m) }
func (*IndexDocumentsRequest) ProtoMessage()               {}
func (*IndexDocumentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IndexDocumentsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexDocumentsRequest) GetDocuments() []byte {
	if m != nil {
		return m.Documents
	}
	return nil
}

func (m *IndexDocumentsRequest) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

type IndexDocumentsResponse struct {
	Count int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *IndexDocumentsResponse) Reset()                    { *m = IndexDocumentsResponse{} }
func (m *IndexDocumentsResponse) String() string            { return proto1.CompactTextString(m) }
func (*IndexDocumentsResponse) ProtoMessage()               {}
func (*IndexDocumentsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *IndexDocumentsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DeleteDocumentsRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ids       []byte `protobuf:"bytes,2,opt,name=ids,proto3" json:"ids,omitempty"`
	BatchSize int32  `protobuf:"varint,3,opt,name=batchSize" json:"batchSize,omitempty"`
}

func (m *DeleteDocumentsRequest) Reset()                    { *m = DeleteDocumentsRequest{} }
func (m *DeleteDocumentsRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteDocumentsRequest) ProtoMessage()               {}
func (*DeleteDocumentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DeleteDocumentsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteDocumentsRequest) GetIds() []byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *DeleteDocumentsRequest) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

type DeleteDocumentsResponse struct {
	Count int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *DeleteDocumentsResponse) Reset()                    { *m = DeleteDocumentsResponse{} }
func (m *DeleteDocumentsResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeleteDocumentsResponse) ProtoMessage()               {}
func (*DeleteDocumentsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DeleteDocumentsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SearchDocumentsRequest struct {
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	SearchRequest []byte `protobuf:"bytes,2,opt,name=searchRequest,proto3" json:"searchRequest,omitempty"`
}

func (m *SearchDocumentsRequest) Reset()                    { *m = SearchDocumentsRequest{} }
func (m *SearchDocumentsRequest) String() string            { return proto1.CompactTextString(m) }
func (*SearchDocumentsRequest) ProtoMessage()               {}
func (*SearchDocumentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SearchDocumentsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchDocumentsRequest) GetSearchRequest() []byte {
	if m != nil {
		return m.SearchRequest
	}
	return nil
}

type SearchDocumentsResponse struct {
	SearchResult []byte `protobuf:"bytes,1,opt,name=searchResult,proto3" json:"searchResult,omitempty"`
}

func (m *SearchDocumentsResponse) Reset()                    { *m = SearchDocumentsResponse{} }
func (m *SearchDocumentsResponse) String() string            { return proto1.CompactTextString(m) }
func (*SearchDocumentsResponse) ProtoMessage()               {}
func (*SearchDocumentsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *SearchDocumentsResponse) GetSearchResult() []byte {
	if m != nil {
		return m.SearchResult
	}
	return nil
}

func init() {
	proto1.RegisterType((*CreateIndexRequest)(nil), "proto.CreateIndexRequest")
	proto1.RegisterType((*CreateIndexResponse)(nil), "proto.CreateIndexResponse")
	proto1.RegisterType((*DeleteIndexRequest)(nil), "proto.DeleteIndexRequest")
	proto1.RegisterType((*DeleteIndexResponse)(nil), "proto.DeleteIndexResponse")
	proto1.RegisterType((*GetStatsRequest)(nil), "proto.GetStatsRequest")
	proto1.RegisterType((*GetStatsResponse)(nil), "proto.GetStatsResponse")
	proto1.RegisterType((*GetMappingRequest)(nil), "proto.GetMappingRequest")
	proto1.RegisterType((*GetMappingResponse)(nil), "proto.GetMappingResponse")
	proto1.RegisterType((*IndexDocumentRequest)(nil), "proto.IndexDocumentRequest")
	proto1.RegisterType((*IndexDocumentResponse)(nil), "proto.IndexDocumentResponse")
	proto1.RegisterType((*DeleteDocumentRequest)(nil), "proto.DeleteDocumentRequest")
	proto1.RegisterType((*DeleteDocumentResponse)(nil), "proto.DeleteDocumentResponse")
	proto1.RegisterType((*IndexDocumentsRequest)(nil), "proto.IndexDocumentsRequest")
	proto1.RegisterType((*IndexDocumentsResponse)(nil), "proto.IndexDocumentsResponse")
	proto1.RegisterType((*DeleteDocumentsRequest)(nil), "proto.DeleteDocumentsRequest")
	proto1.RegisterType((*DeleteDocumentsResponse)(nil), "proto.DeleteDocumentsResponse")
	proto1.RegisterType((*SearchDocumentsRequest)(nil), "proto.SearchDocumentsRequest")
	proto1.RegisterType((*SearchDocumentsResponse)(nil), "proto.SearchDocumentsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Indigo service

type IndigoClient interface {
	CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error)
	DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	GetMapping(ctx context.Context, in *GetMappingRequest, opts ...grpc.CallOption) (*GetMappingResponse, error)
	IndexDocument(ctx context.Context, in *IndexDocumentRequest, opts ...grpc.CallOption) (*IndexDocumentResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	IndexDocuments(ctx context.Context, in *IndexDocumentsRequest, opts ...grpc.CallOption) (*IndexDocumentsResponse, error)
	DeleteDocuments(ctx context.Context, in *DeleteDocumentsRequest, opts ...grpc.CallOption) (*DeleteDocumentsResponse, error)
	SearchDocuments(ctx context.Context, in *SearchDocumentsRequest, opts ...grpc.CallOption) (*SearchDocumentsResponse, error)
}

type indigoClient struct {
	cc *grpc.ClientConn
}

func NewIndigoClient(cc *grpc.ClientConn) IndigoClient {
	return &indigoClient{cc}
}

func (c *indigoClient) CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error) {
	out := new(CreateIndexResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/CreateIndex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoClient) DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error) {
	out := new(DeleteIndexResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/DeleteIndex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/GetStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoClient) GetMapping(ctx context.Context, in *GetMappingRequest, opts ...grpc.CallOption) (*GetMappingResponse, error) {
	out := new(GetMappingResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/GetMapping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoClient) IndexDocument(ctx context.Context, in *IndexDocumentRequest, opts ...grpc.CallOption) (*IndexDocumentResponse, error) {
	out := new(IndexDocumentResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/IndexDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	out := new(DeleteDocumentResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/DeleteDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoClient) IndexDocuments(ctx context.Context, in *IndexDocumentsRequest, opts ...grpc.CallOption) (*IndexDocumentsResponse, error) {
	out := new(IndexDocumentsResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/IndexDocuments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoClient) DeleteDocuments(ctx context.Context, in *DeleteDocumentsRequest, opts ...grpc.CallOption) (*DeleteDocumentsResponse, error) {
	out := new(DeleteDocumentsResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/DeleteDocuments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoClient) SearchDocuments(ctx context.Context, in *SearchDocumentsRequest, opts ...grpc.CallOption) (*SearchDocumentsResponse, error) {
	out := new(SearchDocumentsResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/SearchDocuments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Indigo service

type IndigoServer interface {
	CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error)
	DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	GetMapping(context.Context, *GetMappingRequest) (*GetMappingResponse, error)
	IndexDocument(context.Context, *IndexDocumentRequest) (*IndexDocumentResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	IndexDocuments(context.Context, *IndexDocumentsRequest) (*IndexDocumentsResponse, error)
	DeleteDocuments(context.Context, *DeleteDocumentsRequest) (*DeleteDocumentsResponse, error)
	SearchDocuments(context.Context, *SearchDocumentsRequest) (*SearchDocumentsResponse, error)
}

func RegisterIndigoServer(s *grpc.Server, srv IndigoServer) {
	s.RegisterService(&_Indigo_serviceDesc, srv)
}

func _Indigo_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/CreateIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).CreateIndex(ctx, req.(*CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indigo_DeleteIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).DeleteIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/DeleteIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).DeleteIndex(ctx, req.(*DeleteIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indigo_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indigo_GetMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).GetMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/GetMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).GetMapping(ctx, req.(*GetMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indigo_IndexDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).IndexDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/IndexDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).IndexDocument(ctx, req.(*IndexDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indigo_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/DeleteDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indigo_IndexDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).IndexDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/IndexDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).IndexDocuments(ctx, req.(*IndexDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indigo_DeleteDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).DeleteDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/DeleteDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).DeleteDocuments(ctx, req.(*DeleteDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indigo_SearchDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).SearchDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/SearchDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).SearchDocuments(ctx, req.(*SearchDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Indigo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Indigo",
	HandlerType: (*IndigoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIndex",
			Handler:    _Indigo_CreateIndex_Handler,
		},
		{
			MethodName: "DeleteIndex",
			Handler:    _Indigo_DeleteIndex_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Indigo_GetStats_Handler,
		},
		{
			MethodName: "GetMapping",
			Handler:    _Indigo_GetMapping_Handler,
		},
		{
			MethodName: "IndexDocument",
			Handler:    _Indigo_IndexDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _Indigo_DeleteDocument_Handler,
		},
		{
			MethodName: "IndexDocuments",
			Handler:    _Indigo_IndexDocuments_Handler,
		},
		{
			MethodName: "DeleteDocuments",
			Handler:    _Indigo_DeleteDocuments_Handler,
		},
		{
			MethodName: "SearchDocuments",
			Handler:    _Indigo_SearchDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/indigo_service.proto",
}

func init() { proto1.RegisterFile("proto/indigo_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x94, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0xc7, 0xdb, 0x6e, 0xd9, 0xb3, 0x9e, 0xa7, 0x7b, 0xe1, 0xb0, 0xb5, 0x59, 0x28, 0x68, 0xb2,
	0x40, 0x94, 0x0b, 0x3a, 0x09, 0x2e, 0xd1, 0xae, 0x36, 0x31, 0x4d, 0x02, 0x21, 0xb9, 0x12, 0x57,
	0x48, 0x28, 0x4b, 0xac, 0x2e, 0x52, 0x9b, 0x84, 0xd8, 0x45, 0xc0, 0xe7, 0xe2, 0x03, 0xa2, 0x38,
	0xce, 0x8b, 0x1d, 0x37, 0x43, 0x5c, 0x25, 0x3e, 0xfe, 0xfb, 0xe7, 0xbf, 0xed, 0x73, 0x0e, 0x78,
	0x69, 0x96, 0x88, 0xe4, 0x22, 0x8a, 0xc3, 0x68, 0x99, 0x7c, 0xe5, 0x2c, 0xfb, 0x1e, 0x05, 0x6c,
	0x2e, 0x83, 0xe8, 0xc8, 0x0f, 0x59, 0x01, 0x5e, 0x65, 0xcc, 0x17, 0xec, 0x36, 0x0e, 0xd9, 0x0f,
	0xca, 0xbe, 0x6d, 0x18, 0x17, 0x88, 0xb0, 0x1b, 0xfb, 0x6b, 0xe6, 0xf6, 0xcf, 0xfb, 0xb3, 0x21,
	0x95, 0xff, 0xe8, 0xc2, 0x7f, 0x6b, 0x3f, 0x4d, 0xa3, 0x78, 0xe9, 0x0e, 0xce, 0xfb, 0xb3, 0x11,
	0x2d, 0x87, 0xb9, 0x5a, 0xfc, 0x4c, 0x99, 0xbb, 0x53, 0xa8, 0xf3, 0x7f, 0x3c, 0x01, 0x87, 0x8b,
	0x24, 0x63, 0xee, 0xae, 0x0c, 0x16, 0x03, 0xf2, 0x0a, 0x1e, 0x6b, 0xbb, 0xf1, 0x34, 0x89, 0x39,
	0xb3, 0x6d, 0x47, 0x66, 0x80, 0xd7, 0x6c, 0xc5, 0x1e, 0x36, 0x96, 0x43, 0x35, 0x65, 0x07, 0xf4,
	0x05, 0x1c, 0xdd, 0x30, 0xb1, 0x10, 0xbe, 0xe0, 0x5d, 0xc4, 0x19, 0x1c, 0xd7, 0x32, 0x85, 0x93,
	0x07, 0xf2, 0x05, 0x97, 0xc2, 0x11, 0x2d, 0x06, 0xe4, 0x25, 0x3c, 0xba, 0x61, 0xe2, 0x63, 0x71,
	0x11, 0x5d, 0xc8, 0x39, 0x60, 0x53, 0xa8, 0xa0, 0x8d, 0x3b, 0xed, 0x6b, 0x77, 0x4a, 0x3e, 0xc3,
	0x89, 0x3c, 0xce, 0x75, 0x12, 0x6c, 0xd6, 0x2c, 0x16, 0x5d, 0x2f, 0x73, 0x08, 0x83, 0x28, 0x94,
	0x8f, 0x32, 0xa4, 0x83, 0x28, 0x44, 0x0f, 0xf6, 0x43, 0xb5, 0x4c, 0xbe, 0xc9, 0x88, 0x56, 0x63,
	0xf2, 0x1a, 0x4e, 0x0d, 0x6e, 0x7d, 0xbe, 0x20, 0xd9, 0xc4, 0x42, 0x92, 0x1d, 0x5a, 0x0c, 0xc8,
	0x3b, 0x38, 0x2d, 0xee, 0xf6, 0x1f, 0x7c, 0x90, 0x39, 0x8c, 0xcd, 0xc5, 0x9d, 0x9b, 0x2d, 0x0d,
	0x6f, 0x5d, 0x6f, 0x84, 0x53, 0x18, 0x96, 0x87, 0xe2, 0x2a, 0x21, 0xeb, 0x40, 0x3e, 0x7b, 0xe7,
	0x8b, 0xe0, 0x7e, 0x11, 0xfd, 0x2a, 0xf2, 0xd2, 0xa1, 0x75, 0x20, 0x37, 0x66, 0x6e, 0xd4, 0x69,
	0xec, 0x8b, 0x79, 0x90, 0x4e, 0x67, 0xc7, 0xb0, 0x13, 0x85, 0xa5, 0xa7, 0xfc, 0xf7, 0x01, 0x37,
	0x17, 0x30, 0x69, 0xd1, 0x3b, 0xed, 0x50, 0x18, 0x2f, 0x98, 0x9f, 0x05, 0xf7, 0x7f, 0x65, 0xe7,
	0x39, 0x1c, 0x70, 0xa9, 0x56, 0x22, 0x65, 0x4c, 0x0f, 0x92, 0x4b, 0x98, 0xb4, 0x98, 0xca, 0x04,
	0x81, 0x51, 0xa9, 0xe5, 0x9b, 0x95, 0x50, 0x99, 0xaa, 0xc5, 0xde, 0xfc, 0x76, 0x60, 0xef, 0x56,
	0xb6, 0x19, 0x7c, 0x0f, 0xff, 0x37, 0x6a, 0x1c, 0xcf, 0x8a, 0x7e, 0x33, 0x6f, 0x77, 0x19, 0xcf,
	0xb3, 0x4d, 0x15, 0x9b, 0x92, 0x5e, 0xce, 0x69, 0x94, 0x75, 0xc5, 0x69, 0x37, 0x85, 0x8a, 0x63,
	0xe9, 0x02, 0xa4, 0x87, 0x97, 0xb0, 0x5f, 0x16, 0x33, 0x8e, 0x95, 0xd2, 0x68, 0x02, 0xde, 0xa4,
	0x15, 0xaf, 0x96, 0x5f, 0x01, 0xd4, 0x85, 0x8b, 0x6e, 0x2d, 0xd4, 0x8b, 0xde, 0x3b, 0xb3, 0xcc,
	0x54, 0x90, 0x0f, 0x70, 0xa0, 0x25, 0x1c, 0x3e, 0x51, 0x6a, 0x5b, 0x8d, 0x7b, 0x53, 0xfb, 0x64,
	0x45, 0xfb, 0x04, 0x87, 0x7a, 0xc2, 0xe0, 0x54, 0xbb, 0x01, 0x93, 0xf7, 0x74, 0xcb, 0x6c, 0x13,
	0xa8, 0xd7, 0x03, 0x5a, 0x2d, 0x70, 0x13, 0x68, 0x2f, 0x22, 0xd2, 0x43, 0x0a, 0x47, 0x46, 0x4a,
	0xa3, 0xdd, 0x44, 0x85, 0x7c, 0xb6, 0x6d, 0xba, 0xc9, 0x34, 0x32, 0xb4, 0x62, 0xda, 0xab, 0xa1,
	0x62, 0x6e, 0x49, 0x6c, 0xd2, 0xbb, 0xdb, 0x93, 0x82, 0xb7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x5f, 0x33, 0xc6, 0x73, 0x29, 0x07, 0x00, 0x00,
}
