// Code generated by protoc-gen-go.
// source: proto/indigo_service.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/indigo_service.proto

It has these top-level messages:
	MappingRequest
	MappingResponse
	IndexRequest
	DeleteRequest
	IndexResponse
	SearchRequest
	SearchResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type MappingRequest struct {
}

func (m *MappingRequest) Reset()                    { *m = MappingRequest{} }
func (m *MappingRequest) String() string            { return proto1.CompactTextString(m) }
func (*MappingRequest) ProtoMessage()               {}
func (*MappingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MappingResponse struct {
	Mapping string `protobuf:"bytes,1,opt,name=mapping" json:"mapping,omitempty"`
}

func (m *MappingResponse) Reset()                    { *m = MappingResponse{} }
func (m *MappingResponse) String() string            { return proto1.CompactTextString(m) }
func (*MappingResponse) ProtoMessage()               {}
func (*MappingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MappingResponse) GetMapping() string {
	if m != nil {
		return m.Mapping
	}
	return ""
}

type IndexRequest struct {
	Documents string `protobuf:"bytes,1,opt,name=documents" json:"documents,omitempty"`
	BatchSize int32  `protobuf:"varint,2,opt,name=batchSize" json:"batchSize,omitempty"`
}

func (m *IndexRequest) Reset()                    { *m = IndexRequest{} }
func (m *IndexRequest) String() string            { return proto1.CompactTextString(m) }
func (*IndexRequest) ProtoMessage()               {}
func (*IndexRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IndexRequest) GetDocuments() string {
	if m != nil {
		return m.Documents
	}
	return ""
}

func (m *IndexRequest) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

type DeleteRequest struct {
	Ids       string `protobuf:"bytes,1,opt,name=ids" json:"ids,omitempty"`
	BatchSize int32  `protobuf:"varint,2,opt,name=batchSize" json:"batchSize,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteRequest) GetIds() string {
	if m != nil {
		return m.Ids
	}
	return ""
}

func (m *DeleteRequest) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

type IndexResponse struct {
	DocumentCount int32 `protobuf:"varint,1,opt,name=documentCount" json:"documentCount,omitempty"`
}

func (m *IndexResponse) Reset()                    { *m = IndexResponse{} }
func (m *IndexResponse) String() string            { return proto1.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()               {}
func (*IndexResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IndexResponse) GetDocumentCount() int32 {
	if m != nil {
		return m.DocumentCount
	}
	return 0
}

type SearchRequest struct {
	Request string `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto1.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SearchRequest) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

type SearchResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto1.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SearchResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto1.RegisterType((*MappingRequest)(nil), "proto.MappingRequest")
	proto1.RegisterType((*MappingResponse)(nil), "proto.MappingResponse")
	proto1.RegisterType((*IndexRequest)(nil), "proto.IndexRequest")
	proto1.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto1.RegisterType((*IndexResponse)(nil), "proto.IndexResponse")
	proto1.RegisterType((*SearchRequest)(nil), "proto.SearchRequest")
	proto1.RegisterType((*SearchResponse)(nil), "proto.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Indigo service

type IndigoClient interface {
	Mapping(ctx context.Context, in *MappingRequest, opts ...grpc.CallOption) (*MappingResponse, error)
	Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type indigoClient struct {
	cc *grpc.ClientConn
}

func NewIndigoClient(cc *grpc.ClientConn) IndigoClient {
	return &indigoClient{cc}
}

func (c *indigoClient) Mapping(ctx context.Context, in *MappingRequest, opts ...grpc.CallOption) (*MappingResponse, error) {
	out := new(MappingResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/Mapping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoClient) Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	out := new(IndexResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/Index", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	out := new(IndexResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/proto.Indigo/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Indigo service

type IndigoServer interface {
	Mapping(context.Context, *MappingRequest) (*MappingResponse, error)
	Index(context.Context, *IndexRequest) (*IndexResponse, error)
	Delete(context.Context, *DeleteRequest) (*IndexResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterIndigoServer(s *grpc.Server, srv IndigoServer) {
	s.RegisterService(&_Indigo_serviceDesc, srv)
}

func _Indigo_Mapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).Mapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/Mapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).Mapping(ctx, req.(*MappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indigo_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/Index",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).Index(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indigo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indigo_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Indigo/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Indigo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Indigo",
	HandlerType: (*IndigoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mapping",
			Handler:    _Indigo_Mapping_Handler,
		},
		{
			MethodName: "Index",
			Handler:    _Indigo_Index_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Indigo_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Indigo_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/indigo_service.proto",
}

func init() { proto1.RegisterFile("proto/indigo_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x8d, 0x92, 0x84, 0x5e, 0x4c, 0x2d, 0xa3, 0x2d, 0x21, 0xb8, 0x28, 0x83, 0x8b, 0x88,
	0x50, 0xc1, 0x5f, 0x70, 0xe3, 0x42, 0x37, 0x15, 0xdc, 0xa4, 0x0f, 0x20, 0x69, 0x72, 0x69, 0x07,
	0xda, 0x99, 0x98, 0x99, 0x88, 0xf8, 0xca, 0xbe, 0x84, 0x74, 0x7e, 0x52, 0x53, 0x10, 0x57, 0x99,
	0xf9, 0x72, 0xce, 0xb9, 0x73, 0x0f, 0x24, 0x55, 0x2d, 0x94, 0xb8, 0x64, 0xbc, 0x64, 0x0b, 0xf1,
	0x26, 0xb1, 0xfe, 0x60, 0x05, 0x4e, 0x34, 0x24, 0xbe, 0xfe, 0xd0, 0x01, 0xf4, 0x5f, 0xf3, 0xaa,
	0x62, 0x7c, 0x91, 0xe1, 0x7b, 0x83, 0x52, 0xd1, 0x0b, 0x38, 0x6a, 0x89, 0xac, 0x04, 0x97, 0x48,
	0x62, 0x08, 0xd7, 0x06, 0xc5, 0xde, 0xd8, 0x4b, 0x7b, 0x99, 0xbb, 0xd2, 0x17, 0x38, 0x9c, 0xf2,
	0x12, 0x3f, 0xad, 0x99, 0x9c, 0x42, 0xaf, 0x14, 0x45, 0xb3, 0x46, 0xae, 0xa4, 0xd5, 0x6e, 0xc1,
	0xe6, 0xef, 0x3c, 0x57, 0xc5, 0x72, 0xc6, 0xbe, 0x30, 0xde, 0x1f, 0x7b, 0xa9, 0x9f, 0x6d, 0x01,
	0x7d, 0x84, 0xe8, 0x19, 0x57, 0xa8, 0xd0, 0x85, 0x0d, 0xe0, 0x80, 0x95, 0x2e, 0x66, 0x73, 0xfc,
	0x27, 0xe0, 0x16, 0x22, 0xfb, 0x18, 0xfb, 0xee, 0x33, 0x88, 0xdc, 0xf0, 0x27, 0xd1, 0x70, 0xa5,
	0xa3, 0xfc, 0xac, 0x0b, 0xe9, 0x39, 0x44, 0x33, 0xcc, 0xeb, 0x62, 0xe9, 0xe6, 0xc6, 0x10, 0xd6,
	0xe6, 0xe8, 0xd6, 0xb5, 0x57, 0x9a, 0x42, 0xdf, 0x49, 0xed, 0x88, 0x11, 0x04, 0x35, 0xca, 0x66,
	0xe5, 0xa4, 0xf6, 0x76, 0xf5, 0xed, 0x41, 0x30, 0xd5, 0xbd, 0x93, 0x07, 0x08, 0x6d, 0xa1, 0x64,
	0x68, 0xca, 0x9f, 0x74, 0x2b, 0x4f, 0x46, 0xbb, 0xd8, 0x84, 0xd3, 0x3d, 0x72, 0x03, 0xbe, 0x5e,
	0x89, 0x1c, 0x5b, 0xc9, 0xef, 0xb6, 0x93, 0x93, 0x2e, 0x6c, 0x5d, 0x77, 0x10, 0x98, 0x26, 0x89,
	0x53, 0x74, 0x8a, 0xfd, 0xd3, 0x77, 0x0f, 0x81, 0x59, 0xaf, 0xf5, 0x75, 0x8a, 0x49, 0x86, 0x3b,
	0xd4, 0x19, 0xe7, 0x81, 0xe6, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x57, 0x1d, 0x2b, 0x94,
	0x71, 0x02, 0x00, 0x00,
}
